### ISSUE TITLE
docs: provide rating and feedback mechanism

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/plugin-tools#1006]
Similar to what we have on the main [grafana docs](https://github.com/grafana/website/blob/9a0f206c9ea84d7301e410291e78beaa1001129b/layouts/partials/docs/rating.html)

<img width="886" alt="Screenshot 2024-07-12 at 10 51 46" src="https://github.com/user-attachments/assets/b491b093-f6b1-469a-9672-b94bff8c7cb5">

It would be useful to be able to gather insights from users on which pages are more/less helpful and directly encourage feedback.

A quick search suggests no docusaurus plugin exists for this and instead the recommendation seems to be to [swizzle](https://docusaurus.io/docs/swizzling)

**Comment by derek-cadzow** [comment]
@josmperez  Is this our task and should it stay in our repo/project?

**Comment by josmperez** [comment]
> @josmperez Is this our task and should it stay in our repo/project?

This task will require engneering resources to complete and none have yet been assigned; however, @jdbaldry is aware of this to-do and he may be taking a look at it in the future (or someone on the plugins team could be assigned to it).

**Comment by jdbaldry** [comment]
It's not something that I'll be actively working on in the current quarter for sure.

Here's a starting point for the implementation in the website: https://github.com/grafana/website/blob/bc01d9453359ad66e97a70a5753d828817d70c7f/assets/js/app/components/docs.js#L160-L234

**Comment by sympatheticmoose** [comment]
I'd expect we'd own it in the plugins team, but would want to collab as appropriate to leverage whats already in place. Ideally we'd want to be able to measure consistently as there are some journeys which will span both the grafana docs and the dev docs

**Comment by jdbaldry** [comment]
In theory, you can use the same code right? You'd just need to hook up an element similar to ours https://github.com/grafana/website/blob/ac8baa261059cf8670d5ecc40cdf755a10cbf840/layouts/partials/docs/rating.html
