### ISSUE TITLE
Bug: toHaveAlert has an incorrect return type

### ISSUE THREAD

**Issue by academo** [grafana/plugin-tools#1010]
when using toHaveAlert the linter reports await has no effect but it is an async function that requires alert

![image](https://github.com/user-attachments/assets/c2ed78b8-bacd-46bd-8566-df8d1a44e828)

https://github.com/grafana/plugin-tools/blob/main/packages/plugin-e2e/src/matchers/toHaveAlert.ts#L7

**Comment by sunker** [comment]
Fixed in https://github.com/grafana/plugin-tools/pull/1070
