### ISSUE TITLE
Docs: Add a doc about using MUX with backend plugins (app and datasources)

### ISSUE THREAD

**Issue by academo** [grafana/plugin-tools#1032]

**Comment by marefr** [comment]
@academo referring to https://grafana.com/developers/plugin-tools/how-to-guides/data-source-plugins/add-router ?

**Comment by academo** [comment]
@marefr partially!

We should extend this to also to call resource

**Comment by marefr** [comment]
@academo the query type mux doesn't apply to call resource, but we do have https://grafana.com/developers/plugin-tools/how-to-guides/data-source-plugins/add-resource-handler#advanced-use-cases and #878 so maybe we can close this?

**Comment by academo** [comment]
@marefr indeed. But the reason I am proposing this is because using mux for resource handler is not an "advance case" it is the default because that's what we use in our examples and that's what we generate in create-plugin.

My proposal is to improve this documentation to make it the default on how to use the resource handler and leave the current documentation as the actual "advance case" which is when people want to use their own resource handler.

**Comment by marefr** [comment]
> My proposal is to improve this documentation to make it the default on how to use the resource handler and leave the current documentation as the actual "advance case" which is when people want to use their own resource handler.

Hmm okay. Not sure I agree, but maybe remove the advanced use case header and rewrite it to explain when you have multiple routes with different methods (GET, POST etc) its recommend to use a mux? Feel free to update the issue description
