### ISSUE TITLE
Docs: Document how to connect over websocket thru datasource proxy

### ISSUE THREAD

**Issue by marefr** [grafana/plugin-tools#1091]
Documentation is needed for how to be able to connect over websocket thru the Grafana datasource proxy. Maybe here: https://grafana.com/docs/grafana/latest/developers/plugins/add-authentication-for-data-source-plugins/

Basically plugin developer need to convert configured http/https datasource URL to a ws/wss before calling the Grafana datasource proxy, e.g. https://github.com/grafana/grafana/blob/32b76aaf88d021143cce76ede0ec4072eb519fe8/public/app/plugins/datasource/loki/datasource.ts#L252

**Comment by josmperez** [comment]
> Per discussion with [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/sympatheticmoose?size=32">@sympatheticmoose](https://github.com/sympatheticmoose), this is not a doc priority at this time.

Per this note, closing this issue.
