### ISSUE TITLE
Feat: Replace random walk in provisioned panel dashboard

### ISSUE THREAD

**Issue by jackw** [grafana/plugin-tools#1112]
### Which areas does this feature request relate to

- [x] Create Plugin
- [ ] Sign Plugin
- [ ] Plugin E2E
- [ ] Plugin Meta Extractor
- [ ] Documentation

### Problem

Feedback suggests developers that are new to Grafana plugins or dataframes find the random walk datasource quite confusing as it's not explicit what a dataframe looks like, it changes on every refresh, and it is limited when it comes to controlling what is sent to a panel plugin.

### Solution

Replace the random walk datasource that is currently set in the panel plugins provisioned dashboard with either:

- test data datasource set to "raw frames"
- replace test data datasource with [static datasource](https://grafana.com/grafana/plugins/marcusolsson-static-datasource/)

Either of these options should solve this issue and help developers to more easily build their panel plugin.

### Are you interested in contributing the solution?

- [ ] Yes
- [ ] No

**Comment by s4kh** [comment]
@jackw 
These are the provisioned panel plugins in the dashboard, right?
![Image](https://github.com/user-attachments/assets/e8d0ee00-79b1-4d90-8ff7-f88ea5440fae)
But would the data incoming based on the configured datasource in the dashboard? How to configure random walk datasource?

**Comment by jackw** [comment]
@s4kh if you scaffold a new panel plugin (`npx -y @grafana/create-plugin@latest --pluginName='myplugin' --orgName='myorg' --pluginType='panel'`) and follow the instructions to get started once you fire up localhost:3000 there will be a dashboard already provisioned for your plugin.

![Image](https://github.com/user-attachments/assets/2bcbad47-726b-46f3-a873-1dd2095b1e02)

From what I've understood the feedback we've had suggests that this "random walk" isn't particularly helpful to developers that aren't familiar with dataframes.

To solve this we need to make changes to the dashboard provisioning within the create-plugin package - [this is the json file](https://github.com/grafana/plugin-tools/blob/main/packages/create-plugin/templates/panel/provisioning/dashboards/dashboard.json#L42-L51). You can edit the dashboard in the ui and export the json when you have something that's working rather than attempt to edit the json manually.

The options are to either use the testdata db raw frames scenario or to use a plugin such as the static datasource so developers can manually tweak the dataset when they feel the need to. [The `panel-basic` plugin example](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/panel-basic) does this with static datasource.

Let me know if that helps clear things up and feel free to reach out if you have any further questions.
