### ISSUE TITLE
Bug: Dashboard Page fixture doens't work properly for dashboardScene feature

### ISSUE THREAD

**Issue by asimonok** [grafana/plugin-tools#1152]
### Which package(s) does this bug affect?

- [ ] Create Plugin
- [ ] Sign Plugin
- [x] Plugin E2E
- [ ] Plugin Meta Extractor

### Package versions

@grafana/plugin-e2e: 1.8.2

Grafana version: 11.3.0

### What happened?

`await dashboardPage.addPanel()` failes the e2e tets with the error:

```
Error: locator.click: Test timeout of 30000ms exceeded.
Call log:
  - waiting for locator('[data-testid="data-testid Add button"]')
```

It happens because there is no Add Button on the page until Edit mode is not activated. The same with `editPage.apply()` because there is no the button anymore (Back to dashboard button instead)

### What you expected to happen

DashboardPage and PanelEditPage fixtures should be adjusted to support working with Dashboard Scene without tests code change

### How to reproduce it (as minimally and precisely as possible)

1. Create e2e test with add and apply panel
```
const editPage = await dashboardPage.addPanel();
await editPage.apply();
```
2. Run test on the grafana with enabled dashboardScene feature
3. Browse the error

### Environment

@grafana/data: ^11.2.0 => 11.2.0 
@grafana/eslint-config: ^7.0.0 => 7.0.0 
@grafana/plugin-e2e: ^1.8.2 => 1.8.2 
@grafana/runtime: ^11.2.0 => 11.2.0 
@grafana/tsconfig: ^2.0.0 => 2.0.0 
@grafana/ui: ^11.2.0 => 11.2.0

**Comment by tolzhabayev** [comment]
@sunker please take a look

**Comment by sunker** [comment]
Many thanks for reporting this @asimonok! We have [tests](https://github.com/grafana/grafana/tree/main/e2e/plugin-e2e/plugin-e2e-api-tests) in Grafana core that continuously checks for breakages in the plugin-e2e apis, but these two issues slipped through. [This](https://github.com/grafana/plugin-tools/pull/1155) PR should address this and it will hopefully be merged soon.

**Comment by asimonok** [comment]
The latest version works for our case. Thanks for the quick fix!
