### ISSUE TITLE
Update shields.io guidance following change in API / query unsupported

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/plugin-tools#1157]
It's likely all readmes using dynamic json badges will be broken due to a change in how they're handling JSONpath after a vulnerability was disclosed. 

We should:
- [x] update the sample readme in `create-plugin`
- [x] post in community forum and slack

Reference Issue: https://github.com/badges/shields/issues/10553

**Comment by tolzhabayev** [comment]
For those finding this issue - until we update the docs:

Example/Reference PR: https://github.com/grafana/grafana-polystat-panel/pull/424

Changes: 
`url` - set to `https://grafana.com/api/plugins/<your-plugin-id>`
`query`- set to `$.downloads` for downloads and `$.version` for version

make sure the `url` and `query` parameter values are `urlencoded` when used.
