### ISSUE TITLE
Question: get "switch" element in E2E test

### ISSUE THREAD

**Issue by vitPinchuk** [grafana/plugin-tools#1251]
How to correctly get the switch element in the main version so that the approach works for older versions as well ?
The Switch element is located in the panel options on the edit page.
![Image](https://github.com/user-attachments/assets/2352b92c-ad1a-4fa8-be94-9a4f6dbb04a5)

Current implementation (works on version 11.3.0 and lower). Find `switch` and toggle it
```js
.editPage
      .getByGrafanaSelector(
        this.editPage.ctx.selectors.components.PanelEditor.OptionsPane.fieldLabel('Business Table Exportable')
      )
      .getByLabel('Toggle switch')
      .click();
```

This does not work in the main version ("version": "11.4.0-204366") 

Can`t get the element (element(s) not found)
```js
      .getByGrafanaSelector(
        this.editPage.ctx.selectors.components.PanelEditor.OptionsPane.fieldLabel('Business Table Exportable')
      )
      .getByLabel('Toggle switch')
```
 
Thanks

**Comment by tolzhabayev** [comment]
@sunker ptal

**Comment by sunker** [comment]
Thanks for raising this issue @vitPinchuk! 

I just raised [this](https://github.com/grafana/plugin-tools/pull/1253/files) PR that introduces a selector that works across multiple versions of Grafana. 

This makes me think plugin-e2e may need to have some kind of abstraction that bridges the gap between different versions of Grafana. I'll try to come up with a solution for this, but in the meantime you can copy the snippet from my PR above and it should work.
