### ISSUE TITLE
add github CI workflow for cypress e2e testing?

### ISSUE THREAD

**Issue by L2D2Grafana** [grafana/plugin-tools#199]
It looks like the unit tests run in ci.yml is it easy enough to add the e2e tests as well? Several repos do this with .drone, but it would be cool to move that to a github action.
[Drone Example](https://github.com/grafana/app-o11y-kwl/pull/51) - mounting the plugin as a volume.

**Comment by jackw** [comment]
Hey @L2D2Grafana, I'm not sure which version of create-plugin you used but I think #81 already solved this issue.
