### ISSUE TITLE
Bug: yarn lint should ignore files in src/lib/*

### ISSUE THREAD

**Issue by briangann** [grafana/plugin-tools#235]
### Which package(s) does this bug affect?

- [X] Create Plugin
- [ ] Sign Plugin

### Package versions

```shell
1.0.3
```

### What happened?

linting results in thousands of errors, sourced from an included src/libs file:

✖ 21454 problems (21454 errors, 0 warnings)
  12600 errors and 0 warnings potentially fixable with the `--fix` option.

### What you expected to happen

should not attempt to lint extra included libs

### How to reproduce it (as minimally and precisely as possible)

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

```shell
System:
    OS: macOS 11.7.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 739.52 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 3.2.3 - ~/.yarn/bin/yarn
    npm: 9.6.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Brave Browser: 112.1.50.121
    Chrome: 112.0.5615.137
    Firefox: 94.0.1
    Safari: 16.4.1
  npmPackages:
    @grafana/data: 9.3.6 => 9.3.6
    @grafana/e2e: 9.3.6 => 9.3.6
    @grafana/e2e-selectors: 9.3.6 => 9.3.6
    @grafana/eslint-config: ^5.1.0 => 5.1.0
    @grafana/runtime: 9.3.6 => 9.3.6
    @grafana/tsconfig: ^1.2.0-rc1 => 1.2.0-rc1
    @grafana/ui: 9.3.6 => 9.3.6
```

### Additional context

changing package.json to have this lint script fixes the issue:

    "lint": "eslint --cache --ignore-path ./.gitignore --ignore-pattern 'src/libs/*' --ext .js,.jsx,.ts,.tsx .",

**Comment by briangann** [comment]
can also be disabled with .eslintrc

```json
{
  "extends": "./.config/.eslintrc",
  "ignorePatterns": ["src/libs/*"]
}
```

might be good to just have it in the .config/.eslintrc from scaffolding

**Comment by jackw** [comment]
> linting results in thousands of errors, sourced from an included src/libs file:

Hmm I'm not sure we should make this a default of the scaffolded eslint config. What exactly is in `src/libs`? Are they minified external libraries from NPM packages? I don't think eslint or the webpack configs would be particularly keen on such things. Maybe I'm missing some history from `@grafana/toolkit` but what is the use case for storing these in a libs directory rather than adding them as a dependency from NPM?

**Comment by briangann** [comment]
src/libs is used exactly for that case - external minified libraries that are either "unpublished" JS libraries, or are npm packages marked as an external (like d3) that can't be used.

i'm using this for "viz.js" and i've seen it used elsewhere, definitely an edge case. might be worth scanning the catalog for others using this option.

**Comment by academo** [comment]
@briangann I recall we discussed this further in person. The best a plugin developer can do in this case is to extend their own eslint config and exclude the directory themselves. I'll go ahead and close this issue.
