### ISSUE TITLE
Bug: Many vulnerabilities found when creating a plugin

### ISSUE THREAD

**Issue by amnonh** [grafana/plugin-tools#248]
### Which package(s) does this bug affect?

- [X] Create Plugin
- [ ] Sign Plugin

### Package versions

```shell
@grafana/create-plugin@1.3.0
```

### What happened?

When creating a new plugin and run install you get prompt for vulnerabilities, before doing any changes to the code.

```
24 vulnerabilities (2 moderate, 18 high, 4 critical)
```
It cannot be resolved with ```npm audit fix```

### What you expected to happen

It should show zero vulnerabilities

### How to reproduce it (as minimally and precisely as possible)

Simply run ```npx @grafana/create-plugin@latest```
followed by 
```
npm install
```

### Environment

```shell
$ npx envinfo --system --binaries --browsers --npmPackages="@grafana/*"

  System:
    OS: Linux 5.14 Fedora 33 (Workstation Edition) 33 (Workstation Edition)
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
    Memory: 42.59 GB / 62.41 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 9.6.5 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 94.0
  npmPackages:
    @grafana/data: 9.3.8 => 9.3.8 
    @grafana/e2e: 9.3.8 => 9.3.8 
    @grafana/e2e-selectors: 9.3.8 => 9.3.8 
    @grafana/eslint-config: ^5.1.0 => 5.1.0 
    @grafana/runtime: 9.3.8 => 9.3.8 
    @grafana/tsconfig: ^1.2.0-rc1 => 1.2.0-rc1 
    @grafana/ui: 9.3.8 => 9.3.8 

```
```


### Additional context

_No response_

**Comment by jackw** [comment]
Many thanks for raising this issue. We do our best to keep dependencies up to date and we do take security seriously. However security vulnerabilities within the NPM ecosystem are by default reported for both production and development dependencies.

The dependencies create-plugin scaffolds are mostly used during development, to run tests, or to produce the static assets of your grafana plugin. In contrast `npm audit` is designed for node applications so by default it looks for issues that would impact running node code in production. However create-plugin is a build tool, it doesn't produce a running node application.

These development dependency reports lead to a lot of false positives and let developers think their newly scaffolded project is vulnerable to attacks in some way. I believe it is better to run `npm audit --omit=dev` to check only the production dependencies for vulnerabilities. Doing so with lastest create-plugin `npx @grafana/create-plugin@latest` (which is 1.4.0 at the time of writing) reports 0 vulnerabilities for the dependencies that would be bundled in production code.

```
npm audit --omit=dev
found 0 vulnerabilities
```

Thanks again for reporting this but given the above I'm going to go ahead and close this issue. However if you do spot an npm audit that reports production dependency related vulnerabilities please feel free to report it and we will do our best to fix it asap.

**Comment by amnonh** [comment]
Moving to 1.4.0 and omitting dev did solve the issue, thank you
