### ISSUE TITLE
Create Plugin: Make migrate / update smarter

### ISSUE THREAD

**Issue by jackw** [grafana/plugin-tools#261]
I think it would be useful if the configs and workflows that we scaffold contain some sort of metadata maybe in the form of a comment at the top of the file so that we can more easily identify which files create-plugin "owns" and the "version" that last created them. The version could also be used as a reference against our changelogs when plugins update their configs.

Related issue: #61

**Comment by sympatheticmoose** [comment]
@sympatheticmoose add clarification on short term goal
