### ISSUE TITLE
Bug: Wrong Code Coverage for JSX

### ISSUE THREAD

**Issue by asimonok** [grafana/plugin-tools#267]
### Which package(s) does this bug affect?

- [X] Create Plugin
- [ ] Sign Plugin

### Package versions

```shell
1.5.0
```

### What happened?

After migration from `@grafana/toolkit` to the new plugin tools. The same code has less coverage that had before. It seems that some issue with coverage tool or jest config exists. The problem is related to all `jsx/tsx` files.

Coverage with default `/.config/jest.config` file (wrong coverage)
100% Statements 63/63
97.01% Branches 65/67
100% Functions 13/13
100% Lines 53/53
<img width="874" alt="default" src="https://github.com/grafana/plugin-tools/assets/15867703/41c4cc38-2f03-4283-a738-44e8042883e1">

Way to fix the issue:

Adjusted `/.config/jest.config` file
```
transform: {
    '^.+\\.(t|j)sx?$': [
      '@swc/jest',
      {
        /**
         * Override sourceMaps with inline to see the correct coverage lines
         */
        sourceMaps: 'inline',
        jsc: {
          parser: {
            syntax: 'typescript',
            tsx: true,
            decorators: false,
            dynamicImport: true,
          },
        },
      },
    ],
  },
```

Coverage with adjusted jest config (correct coverage)
100% Statements 56/56
100% Branches 51/51
100% Functions 11/11
100% Lines 52/52
<img width="809" alt="fixed" src="https://github.com/grafana/plugin-tools/assets/15867703/9a262b0c-fdb7-4a9b-849b-7da7f79c0c14">

### What you expected to happen

Code coverage for JSX is the same for the same code. Code coverage highlights uncovered lines correctly.

### How to reproduce it (as minimally and precisely as possible)

1. Migrate to the plugins tools (1.5.0) of the existing panel plugin
2. Run jest tests with coverage
3. Compare coverage with results before migration

### Environment

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 450.57 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 94.0.1
    Safari: 14.1.2
  npmPackages:
    @grafana/data: 9.5.2 => 9.5.2 
    @grafana/e2e: ^9.5.2 => 9.5.2 
    @grafana/e2e-selectors: ^9.5.2 => 9.5.2 
    @grafana/eslint-config: ^5.1.0 => 5.1.0 
    @grafana/runtime: 9.5.2 => 9.5.2 
    @grafana/tsconfig: ^1.2.0-rc1 => 1.2.0-rc1 
    @grafana/ui: 9.5.2 => 9.5.2
```

### Additional context

Tests packages versions

```
"jest": "^29.5.0",
"jest-environment-jsdom": "^29.5.0",
"@testing-library/jest-dom": "^5.16.5",
"@testing-library/react": "^14.0.0",
```

**Comment by jackw** [comment]
Many thanks for raising this issue @asimonok . It looks like the [underlying issue](https://github.com/swc-project/swc/issues/3854) is indeed related to `swc`. Switching to `inline` source maps is one of the suggestions in that issue so it looks like a good addition to me. 👍 

Would you be willing to open a PR with the fix?
