### ISSUE TITLE
update docker-compose file to permit unsigned signatures

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/plugin-tools#275]
Need to set `GF_DEFAULT_APP_MODE=development` so the plugin successfully loads

**Comment by academo** [comment]
@sympatheticmoose we already set it to development when we build the image https://github.com/grafana/plugin-tools/blob/main/packages/create-plugin/templates/common/.config/Dockerfile#L12

Did you encounter any problem loading the plugin using the generated setup?
