### ISSUE TITLE
Bug: Hangup on "Run e2e tests"

### ISSUE THREAD

**Issue by 6nv** [grafana/plugin-tools#283]
### Which package(s) does this bug affect?

- [X] Create Plugin
- [ ] Sign Plugin

### Package versions

This command doesn't work for me. But the version number is **1.6.3**

### What happened?

The step "Run e2e tests" in `ci.yml` gets stuck.

### What you expected to happen

The step "Run e2e tests" in `ci.yml` not to get stuck.

### How to reproduce it (as minimally and precisely as possible)

1. Run `npx @grafana/create-plugin@latest` (v1.6.3)
2. Say "yes" to workflows
3. Push to Github

### Environment

```shell
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M2
    Memory: 4.99 GB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 114.1.52.126
    Chrome: 105.0.5195.102
    Firefox: 112.0.2
    Safari: 16.5
```

### Additional context

Please see https://community.grafana.com/t/bug-report-starter-plugin-workflow-gets-hung-up-on-run-e2e-tests/89775 for details.

**Comment by tolzhabayev** [comment]
thank you for the heads up - is it a case of this step constantly hanging up on github actions or does it only happen sporadically? We also run similar workflows ourselves - [here](https://github.com/grafana/grafana-plugin-examples/blob/main/.github/workflows/integration-tests.yml#L157) and have recently added some retry capability in order to reduce flakiness of github actions.

**Comment by 6nv** [comment]
When I posted this message, but it seemed to have been getting stuck every time. That was about 3 weeks ago according to this issue's timestamp. I haven't ran it recently. Maybe these lines are worth adding to the default starter plugin? 30 minutes x3 retries seems a bit long. But if the job gets stuck, I don't think it should necessarily fail the entire workflow.

https://github.com/grafana/grafana-plugin-examples/blob/b2444c1fca96b18dcebf28ff75c3bc06bfe0f598/.github/workflows/integration-tests.yml#L154-L156

**Comment by mikhail-vl** [comment]
We had the same issue, when recorded our tutorials. We used our custom Docker image instead of tool's Dockerfile, which resolved the issue.

  There is something in the Docker build, which keep it running indefinitely. It may be auto-reload.

**Comment by academo** [comment]
I did some extensive testing of this problem and here are my findings:

* The e2e tests don't indefinitely hang up in CI, they take much much longer. A regular e2e tests CI run for the generated panel plugin runs in under 2 minutes (video: false) and over 15 minutes (video: true). But it finishes and passes.
* The problem only exists in tests using grafana e2e scenarios with grafana images above 9.5.0 and recording videos in CI. This is the exact scenario that currently create-plugin generates.
* What is the reason behind this combination of factors fail? Most likely there's a bug in cypress related to after and afterAll hooks that the grafana-e2e-scenarios code extensively uses. The version of cypress that grafana currently uses is old and doesn't get any more updates. Several issues can be found with this problem and they all point to versions of Cypress >=10 that don't have the problem.
* This problem only exists in Github CI with video capturing. There cypress is stuck in a loop of `cypress:server:browsers:electron debugger: sending Page.screencastFrameAck with params` that eventually ends in a video artifact with a frozen frame after a few seconds of run.'

To properly fix this problem we are working in migration grafana to cypress 12 and therefore the plugins configuration to use it.

For now here's what you can do to prevent this slowness problem in CI.

create a `cypress.json` file in the root of your project with the following content:

```
{
  "video": false
}```

**Comment by mikhail-vl** [comment]
@academo Thank you for looking into it. I have not waited for longer than 10 minutes because normally E2E tests should pass within 2-3 minutes as you said.

  As I mentioned, in our E2E workflow we record video, and it works with our custom image. Disabling video can be an option, but it's more of a workaround, and it's harder to troubleshoot when writing tests.

  Looking forward to using Cypress 12 when ready.

**Comment by academo** [comment]
As we'll be working in the migration to cypress 12 in other issues and the e2e tests don't really hang but taking long I'll close this issue.
