### ISSUE TITLE
When signing custom plugin I get the error self-signed certificate in chain

### ISSUE THREAD

**Issue by namoona1** [grafana/plugin-tools#290]
I am trying to sign a custom plugin using the command npx @grafana/toolkit plugin:sign --rootUrls http://localhost:3000/, I am behind a corporate proxy that does SSL inspection of traffic. I have tried everything listed below and still keep getting the message “Self-signed certificate in chain” when trying to sign the plugin.

I have done the following so far

- npm config set constrict-ssl false
- npm config set cafile /path/to/cert.pem
- export NODE_EXTRA_CA_CERTS=\bundle.pem
- set my proxy correctly i.e. proxy and https-proxy for npm
- npm config set ca “cert string”
- Tried setting NODE_TLS_REJECT_UNAUTHORIZED=0

I also ran NODE_DEBUG=‘tls,https’ npx @grafana/toolkit plugin:sign --rootUrls http://localhost:3000/ to see if my certificates are being picked up correctly. 

I am 100% sure my certificates are correct as I verified they work using curl -v --cacert bundle.pem https://grafana.pem and I get data from grafana.com

Nothing seems to solve the problem, I am suspecting the libraries being used are ignoring NPM settings

**Comment by namoona1** [comment]
I tried it this way export NODE_TLS_REJECT_UNAUTHORIZED=0; npx @grafana/sign-plugin@latest --rootUrls https://localhost:3000, I do receive the warning you listed above however it still complains about the self-signed certificate. I will try it the way you recommended also

**Comment by namoona1** [comment]
Thank you so much @academo I can confirm this via a corporate proxy the only thing is I had to do differently was run it as NODE_TLS_REJECT_UNAUTHORIZED=0 npx @grafana/sign-plugin@latest --rootUrls https://localhost:3000

**Comment by academo** [comment]
Great to hear @namoona1 I'll go ahead and close this issue as the PR is merged and released in the latest version.
