### ISSUE TITLE
Update create-tool to detect and correctly ask to update the cypress configuration if grafana/e2e 10.1.x is detected and an old cypress configuration is detected.

### ISSUE THREAD

**Issue by academo** [grafana/plugin-tools#300]
Requisites: https://github.com/grafana/grafana/pull/60117 merged

We should detect if the e2e package dependency is higher or equal to 10.1.x, detect if the old cypress configuration is in place and prompt the user to update the cypress configuration for cypress 12

**Comment by jackw** [comment]
This was superseded by the plugin-e2e.
