### ISSUE TITLE
Bug: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by EugeneLazutin** [grafana/plugin-tools#304]
### Which package(s) does this bug affect?

- [X] Create Plugin
- [ ] Sign Plugin

### Package versions

```shell
1.9.0
```

### What happened?

After the last question I recieve 'Cannot read property 'split' of undefined' error

### What you expected to happen

New plugin created

### How to reproduce it (as minimally and precisely as possible)

1. Using WSL 2 console (Ubuntu 22.04.2 LTS)
2. Run 'npx @grafana/create-plugin@latest'
3. Aswer 6 questions
4. See error 'Cannot read property 'split' of undefined'

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900K
    Memory: 18.06 GB / 31.19 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.21.3/bin/yarn
    npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
```

**Comment by sympatheticmoose** [comment]
Hi @EugeneLazutin could you expand on

> Answer 6 questions

So we can understand which type of plugin you were creating?

**Comment by EugeneLazutin** [comment]
Sure, I'm trying to create a panel plugin, here's the full text

> npx @grafana/create-plugin@latest
? What is going to be the name of your plugin? plugin
? What is the organization name of your plugin? test
? How would you describe your plugin? test
? What type of plugin would you like? panel
? Do you want to add Github CI and Release workflows? No
? Do you want to add a Github workflow for automatically checking "Grafana API compatibility" on PR
s? No
⠋ [ERROR] Cannot read property 'split' of undefined

**Comment by tolzhabayev** [comment]
@EugeneLazutin could you try it with a [node version](https://github.com/grafana/plugin-tools/blob/main/packages/create-plugin/package.json#L67) of 16+?

**Comment by EugeneLazutin** [comment]
@tolzhabayev thank you. Works fine using node v16.20.1.

I gues it would be nice to update prerequisites in [documentation](https://grafana.com/docs/grafana/latest/developers/plugins/create-a-grafana-plugin/develop-a-plugin/build-a-panel-plugin/) as it says node v14 should work

**Comment by sympatheticmoose** [comment]
Thanks for pointing that out - we'll get it updated asap
