### ISSUE TITLE
Bug: plugin signature not working behind a proxy

### ISSUE THREAD

**Issue by papaux** [grafana/plugin-tools#310]
### Which package(s) does this bug affect?

- [ ] Create Plugin
- [X] Sign Plugin

### Package versions

```shell
@grafana/sign-plugin@1.0.3
```

### What happened?

After the upgrade to v1.0.3 of sign-plugin, we cannot anymore sign plugins when running behind a HTTPS proxy.

The issue has been introduced by this change, where it replaced `axios` by a plain request from `https` module:
https://github.com/grafana/plugin-tools/pull/292

Axios honors out of the box the `https_proxy` config from the environment if set, as highlighted here: https://www.scrapingbee.com/blog/nodejs-axios-proxy/

Which is not the case with https module, it requires explicit proxy config as far as I understand.

I confirmed by reverting to @grafana/sign-plugin@1.0.2 and the plugin signature works as expected.

Maybe there is another way to set the proxy, but I don't see it from the config here:
https://nodejs.org/api/http.html#httprequestoptions-callback

### What you expected to happen

Signature should work when behind a proxy.

### How to reproduce it (as minimally and precisely as possible)

1. Set the environment variable `https_proxy` to use a proxy server
2. Close all direct internet access
3. Run plugin signature with the old / new version

### Environment

```shell
N/A but environment should not matter.
```

**Comment by academo** [comment]
Hi @papaux would you be able to contribute a PR to include support for https_proxy ?

**Comment by Waxolunist** [comment]
Why not instead use again axios? This was an unneccessary change.

**Comment by academo** [comment]
> Why not instead use again axios? This was an unneccessary change.

Axios was causing different problems  in other scenarios see https://github.com/grafana/plugin-tools/issues/290

I opened a PR to enable https_proxy support here https://github.com/grafana/plugin-tools/pull/436
