### ISSUE TITLE
docs: provide guidance on bundling dashboards

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/plugin-tools#372]
Plugins can include dashboards to help users get started quickly. 

We should provide basic instructions on how to bundle a dashboard, as well as guidance around [update considerations](https://raintank-corp.slack.com/archives/C024NL6AEJH/p1692608013632919). 

Under the current structure, this should come under the `Extend a plugin` category

**Comment by josmperez** [comment]
i don't understand why the bot closed this as done. Re-opening.

**Comment by josmperez** [comment]
@jackw - Jack since you contributed the linked Slack comment above, is this a topic where you can draft the technical content?

**Comment by josmperez** [comment]
Hi @jackw - Do you have bandwidth to draft something for this PR in Q4?

**Comment by jackw** [comment]
@josmperez I might be able to draft something for this by end of next week?
