### ISSUE TITLE
Docs: Can plugins be renamed?

### ISSUE THREAD

**Issue by josmperez** [grafana/plugin-tools#384]
### Which areas does this feature request relate to

- [ ] Create Plugin
- [ ] Sign Plugin
- [X] Documentation

### Problem

Consider documenting answer to this question. 

### Solution

"once published it is difficult, there's a new feature in 10.1 that will allow aliasing, but it won't work for older versions of grafana" 

See internal discussion here: https://raintank-corp.slack.com/archives/C01C4K8DETW/p1693421748284749

### Are you interested in contributing the solution?

- [ ] Yes
- [ ] No

**Comment by sympatheticmoose** [comment]
They can't be renamed yet, there is ongoing work to enable this - for now the alias function is only available internally as requires hardcorded values.
