### ISSUE TITLE
Docs: broken links to advanced-configuration.md in Grafana code

### ISSUE THREAD

**Issue by josmperez** [grafana/plugin-tools#385]
### Which areas does this feature request relate to

- [ ] Create Plugin
- [ ] Sign Plugin
- [X] Documentation

### Problem

Grafana user reports "getting a dead link when I follow this from some code, i assume it needs a redirect: https://grafana.github.io/plugin-tools/docs/advanced-configuration#extending-the-typescript-config"

Code is found in many places. See this search:  https://github.com/search?q=org%3Agrafana%20%22https%3A%2F%2Fgrafana.github.io%2Fplugin-tools%2Fdocs%2Fadvanced-configuration%23extending-the-jest-config%22&type=code

See internal Slack discussion: https://raintank-corp.slack.com/archives/C5PG2JK8W/p1693948274101989

### Solution

Add redirect or fix github.com/grafana/ references in batch.

### Are you interested in contributing the solution?

- [ ] Yes
- [ ] No

**Comment by sympatheticmoose** [comment]
We likely want to hold fire on redirects until the dust has settled more on the developer portal content. 

I've got https://github.com/grafana/plugin-tools/pull/382 which fixes the generated files and our readmes having incorrect URLs

**Comment by josmperez** [comment]
> We likely want to hold fire on redirects until the dust has settled more on the developer portal content.

Agreed.

**Comment by Eve832** [comment]
@josmperez has this already been fixed?

**Comment by josmperez** [comment]
No, moving to backlog with high priority.

**Comment by josmperez** [comment]
At this point this code comment appears in 8 files which are auto-generated (DON'T EDIT THIS FILE DIRECTLY). How to update these links?

**Comment by josmperez** [comment]
Won't fix. See internal conversation [here](https://raintank-corp.slack.com/archives/C024NL6AEJH/p1699397789970879).
