### ISSUE TITLE
Docs: Data source backend plugin tutorial - Wrong instructions

### ISSUE THREAD

**Issue by josmperez** [grafana/plugin-tools#392]
### Which areas does this feature request relate to

- [ ] Create Plugin
- [ ] Sign Plugin
- [X] Documentation

### Problem

User reports:

"If I understand correctly, there is no SampleDatasource instead it's now just Datasource
https://grafana.com/docs/grafana/latest/developers/plugins/create-a-grafana-plugin/develop-a-plugin/build-a-data-source-backend-plugin/

### Solution

User reports: "You should add "alerting": true,  not backend."

### Are you interested in contributing the solution?

- [ ] Yes
- [ ] No

**Comment by sympatheticmoose** [comment]
Already fixed in #373
