### ISSUE TITLE
Doc: add-support-for-variables.md is out of date

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/plugin-tools#454]
The add support for variables page suggests to use `setVariableQueryEditor` which is deprecated.

**Comment by andresmgot** [comment]
This is a duplicate of https://github.com/grafana/grafana/issues/63619 (I suggest to upvode that one). Let us know if you think otherwise!

**Comment by zoltanbedi** [comment]
Thanks @andresmgot!
