### ISSUE TITLE
Consider customizing DocCardLists (category indexes)

### ISSUE THREAD

**Issue by josmperez** [grafana/plugin-tools#473]
Background: When designing the website, we decided not to use the Docusaurus DocCardList (category index) feature because it seemed to add nothing of value. However, when creating redirects from the old Hugo site this created the problem that many Hugo index pages had nothing to link to. Subsequently, I created DocCardLists in a few categories where we were most in need of a hook to hang a redirect onto.

This issue captures two things to consider going forward
- Do we add DocCardLists to the rest of the category pages where they don't exist? And subcategory pages where there's more than one subcategory? This would have the advantage of creating a **consistent** user experience.
- Whether we do or don't expand our use of DocCardLists, do we develop custom code logic so that the default text that appears in the cards is of custom length? This would avoid the problem that the first sentences of the topics are all truncated, which proides a less than ideal user experience. 

Google "docusaurus doccardlist custom" for the latest discussion of how Docusaurus may be extended to allow custom category index pages.

**Comment by sympatheticmoose** [comment]
I think the DocCardLists were a great interim solution to satisfy the requirements on redirects. Longer term I would opt for something simpler like the following, but also displaying the metadata description. 
![image](https://github.com/grafana/plugin-tools/assets/19860021/f9b3c08a-c7e3-424e-b253-80c970f3abe2)

The DocCards take up so much space for such low utility, the docs images look like they've failed to load and the folder images are not in keeping with the rest of our look and feel. 

If we have a solution which generates a list of the folder's contents displaying the title and description, I think that would suffice. As part of adding these though, I would like us to consider the additional content we would put on this index/introductory page.

**Comment by josmperez** [comment]
This issue has been mainly fixed by the PR which added DocCardLinks, and[ this pending PR](https://github.com/grafana/plugin-tools/pull/526) which implemented the fix. However, we need to implement creating links based on directories as well as files.

**Comment by josmperez** [comment]
Closing. To track related issue in https://github.com/grafana/plugin-tools/pull/526.
