### ISSUE TITLE
docs: work with frontend needs package manager selector

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/plugin-tools#525]
https://grafana-dev.com/developers/plugin-tools/create-a-plugin/develop-a-plugin/work-with-frontend respects a users previous choice/default, but doesnt allow them to change it on the page

see getting started as example of selector

**Comment by Eve832** [comment]
Can you please take a look @josmperez ?

**Comment by josmperez** [comment]
Got it, will add language tabbing as on "Get started".
