### ISSUE TITLE
Docs: Write new "app" tutorial from scratch, repurposing some legacy content

### ISSUE THREAD

**Issue by josmperez** [grafana/plugin-tools#555]
In the move from repo to repo the app plugin tutorial seems to have got lost in the shuffle. Investigate and move this content as needed:

https://github.com/grafana/tutorials/blob/master/content/tutorials/build-an-app-plugin.md

**Comment by josmperez** [comment]
Per discussion begun by @jackw [here](https://raintank-corp.slack.com/archives/C024NL6AEJH/p1703002028375629?thread_ts=1702943560.113299&cid=C024NL6AEJH), this tutorial needs a thorough review of currency of code samples and a restructuring to move some content into a separate topic.

I'd like to see a developer review the code examples, perhaps @jackw and @oshirohugo (feel free to add others) and review by @sympatheticmoose to determine if tutorial (still) meets product marketing objectives.

**Comment by sympatheticmoose** [comment]
@josmperez suggestion would be to repurpose this issue into one for creating a new app tutorial from scratch and use the content for bundling to act as a starting point for https://github.com/grafana/plugin-tools/issues/372

**Comment by josmperez** [comment]
Hi @jackw and @oshirohugo - David suggests creating a new app tutorial from scratch. Could each of you please confirm your interest in drafting something (separately or together), and if so, if you can complete this task before the end of Q4?

**Comment by jackw** [comment]
@josmperez I don't think I'm going to have the time to write a new app tutorial from scratch before the end of Q4. That's end of next week, right?

**Comment by josmperez** [comment]
Right. Let's tackle this in Q1.

**Comment by josmperez** [comment]
@jackw @oshirohugo - Hi, could you please update me on whether this looks do-able in Q1?
