### ISSUE TITLE
docs: github actions doc reference api keys and miss steps

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/plugin-tools#593]
https://grafana.com/developers/plugin-tools/create-a-plugin/develop-a-plugin/set-up-github-workflows#the-release-workflow

Should be updated to use a cloud access policy and maybe point to https://grafana.com/developers/plugin-tools/publish-a-plugin/sign-a-plugin#generate-an-access-policy-token rather than the publish docs

We also don't document storing the token as a repository secret (is there in the release.yaml itself) which could be in both docs pages referenced above

**Comment by tolzhabayev** [comment]
The favourite topic of @Ukochka :)
