### ISSUE TITLE
Bug: Release action fails when using PNPM

### ISSUE THREAD

**Issue by jackw** [grafana/plugin-tools#617]
### Which package(s) does this bug affect?

- [X] Create Plugin
- [ ] Sign Plugin

### Package versions

```shell
2.10.1
```

### What happened?

Chaosmesh developer scaffolded a plugin with pnpm but the release.yml failed to run [see job here](https://github.com/chaos-mesh/datasource/actions/runs/7256795000/job/19769613322).

Errored with: `/home/runner/work/_actions/grafana/plugin-actions/release/build-plugin/pm.sh: line 24: pnpm: command not found`

### What you expected to happen

For the release.yml workflow to run without failure when scaffolding with pnpm.

### How to reproduce it (as minimally and precisely as possible)

1. Scaffold a plugin with pnpm - `pnpm exec @grafana/create-plugin@latest`
2. Make sure to include github workflows
3. Try to run the release workflow with a git tag
4. See error...

### Environment

```shell
N/A
```

### Additional context

The solution (checking for pnpm as a package manager) can likely be copied over from one of the other existing workflow templates.

**Comment by academo** [comment]
Solved in https://github.com/grafana/plugin-actions/pull/11
