### ISSUE TITLE
Feat: Option to disable "Value:" label for pie charts

### ISSUE THREAD

**Issue by nbase-apsleyfarms** [grafana/plugin-tools#648]
### Which areas does this feature request relate to

- [ ] Create Plugin
- [ ] Sign Plugin
- [ ] Documentation

### Problem

Were trying to set up a minimalistic dashboard that only shows the vales without the prepended "Value:". 

### Solution

A panel option to hide the "Value:" label before valies are shown in list view. 
This option could also hide the "Value" label above values on the table.

### Additional context

![pie-chart-labels](https://github.com/grafana/plugin-tools/assets/70641337/098fc4da-6244-4435-9296-fe13e1a73a68)

### Are you interested in contributing the solution?

- [ ] Yes
- [x] No

**Comment by sympatheticmoose** [comment]
Hi @nbase-apsleyfarms - this issue doesn't relate to our plugin development tools, I'm curious what led you to this repository? Just in case we can make anything clearer for folks 🙂 

For this I'd suggest reaching out via https://community.grafana.com/c/support/pie-chart/50
