### ISSUE TITLE
Migrate: Env vars break in Windows

### ISSUE THREAD

**Issue by wz2b** [grafana/plugin-tools#71]
When using toolkit create-plugin:migrate this gets generated:

```
    "build": "TS_NODE_PROJECT=\"./.config/webpack/tsconfig.webpack.json\" webpack -c ./.config/webpack/webpack.config.ts --env production",
    "dev": "TS_NODE_PROJECT=\"./.config/webpack/tsconfig.webpack.json\" webpack -w -c ./.config/webpack/webpack.config.ts --env development",
```

but that doesn't seem to be valid in windows - you can't set environment variables that way in windows.  I tried seeing if webpack pays attention to [config](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#config) but it doesn't seem to.

```
 "scripts": {
    "build": "webpack -c ./.config/webpack/webpack.config.ts --env production",
    "dev": "webpack -w -c ./.config/webpack/webpack.config.ts --env development",
     /* ... */
  },
  "config": {
    "TS_NODE_PROJECT": "./.config/webpack/tsconfig.webpack.json"
  },
```

Initially this seemed to work as it runs the right thing:

```
yarn run v1.21.1
$ webpack -w -c ./.config/webpack/webpack.config.ts --env development
```

However, after that there are a lot of other errors.  They all seem to be related to the fact that config didn't actually set TS_NODE_PROJECT...

I noticed webpack has an --env parameter, so I tried this:
```
    "dev": "webpack -w --env TS_NODE_PROJECT=./.config/webpack/tsconfig.webpack.json -c ./.config/webpack/webpack.config.ts --env development",
```

but this didn't work.  Reading [the docs on that](https://webpack.js.org/guides/environment-variables/) that sets a webpack environment variable, which is not the same as an OS environment variable.

Chasing through the cause of this, I found [this old webpack issue that completely describes the problem](https://github.com/webpack/webpack.js.org/issues/2733) and suggests suggest two ideas:
- Install `cross-env` and set the variable that way, also suggested as a solution [here](https://stackoverflow.com/questions/25112510/how-to-set-environment-variables-from-within-package-json)
- Manipulate the environment variable somewhere else, like in webpack.config.ts

That webpack ticket is followed up with [some webpack documentation](https://webpack.js.org/configuration/configuration-languages/) that suggests the cross-env solution is the right one, though I suspect since grafana generates the webpack.config.ts they might have other ideas that don't bring in another dependency.

**Comment by academo** [comment]
HI @wz2b thanks for reporting this issue. It is now addressed in https://github.com/grafana/create-plugin/pull/75 and we'll release an update to the create-plugin package after is merged.
