### ISSUE TITLE
feat: add support for remote debugging in docker development environment

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/plugin-tools#735]
To support a better DX using our recommended workflows, we need to remove the docker incompatibility of our initial support for remote debugging of backend applications. Possibly with use of `dlv attach $(pgrep whatever-is-in-plugin-json.executable)`

As part of this effort we need to reinstate the documentation for using the debugger as this was bundled with local development guidance https://github.com/grafana/plugin-tools/pull/661/files

**Comment by oshirohugo** [comment]
Closed by https://github.com/grafana/grafana-plugin-sdk-go/pull/926
