### ISSUE TITLE
spike: remove need to manually rebuild and restart on backend changes

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/plugin-tools#736]
**Why?**
We need to find a way to update the plugin on backend changes automatically, similarly to how we already do that in the frontend. 

**One possible solution to explore**
- https://tilt.dev/ is also used by some of our cloud app teams. This does not mean we have to use it, it is just a suggestion.

**Comment by Davidkramer1999** [comment]
I would appreciate this feature as well? Until this is resolved, is there a workaround? Because every time restarting Docker image and running mage -v build:linux, I think it will take me quite some time...

**Comment by Ukochka** [comment]
Suggestion from @tolzhabayev ti use https://github.com/cosmtrek/air
