### ISSUE TITLE
Feat: GitHub action to run `yarn create @grafana/plugin update`

### ISSUE THREAD

**Issue by sd2k** [grafana/plugin-tools#818]
### Which areas does this feature request relate to

- [X] Create Plugin
- [ ] Sign Plugin
- [ ] Plugin E2E
- [ ] Documentation

### Problem

I rarely remember that I need to periodically run `yarn create @grafana/plugin update`, unless someone prompts me or I happen to see something in Slack.

### Solution

A GitHub action, similar to dependabot/renovate, which runs `yarn create @grafana/plugin update` in my repository (optionally in a subdirectory) and creates a PR with the changes. I could run this on a schedule to make sure my plugin is regularly updated.

### Are you interested in contributing the solution?

- [ ] Yes
- [ ] No

**Comment by academo** [comment]
Idea to work on this:

Modify this to make it package manager-agnostic and put it in https://github.com/grafana/plugin-actions

https://github.com/jackw/heywesty-trafficlight-panel/blob/main/.github/workflows/create-plugin-update.yml

Then modify the create-plugin template to call this action in a cron

**Comment by jackw** [comment]
[Documentation can be found here](https://grafana.com/developers/plugin-tools/get-started/set-up-development-environment#the-create-plugin-update-workflow) for anyone that would like to add the create plugin update workflow to an existing plugin.
