### ISSUE TITLE
Docs: Need clarification on Long/Wide Formats

### ISSUE THREAD

**Issue by sarahzinger** [grafana/plugin-tools#880]
### Which areas does this feature request relate to

- [ ] Create Plugin
- [ ] Sign Plugin
- [ ] Plugin E2E
- [X] Documentation

### Problem

I'm working on a datasource and reading through the long vs wide data frame section and find myself a bit confused by this line: 

["Grafana can detect and convert data frames in long format into wide format."](https://grafana.com/developers/plugin-tools/introduction/data-frames#long-format:~:text=Grafana%20can%20detect%20and%20convert%20data%20frames%20in%20long%20format%20into%20wide%20format.)

This doesn't happen automatically right? My understanding is that grafana offers some helper functions to make this easier, perhaps we could add docs for that? Or does the timeseries visualization always convert dataframes to wide?

I think it'd also be good to mention here that if developers want to their dataframes to support alerting they need to use wide dataframes

### Solution

Maybe link to the wideToLong and longToWide functions? https://github.com/grafana/grafana-plugin-sdk-go/blob/main/data/time_series.go#L210

### Are you interested in contributing the solution?

- [ ] Yes
- [ ] No

**Comment by derek-cadzow** [comment]
@josmperez  please have a look and unassign if you are unable to fix this one.  Thanks!

**Comment by josmperez** [comment]
Thanks for pointing this out. I'll take a look.

**Comment by josmperez** [comment]
Need engineer tech review (@andresmgot ?) of this suggested fix.

**Comment by andresmgot** [comment]
I agree that the sentence is a bit confusing, maybe @marefr can correct me if I am wrong but it could clarify:

 - When it says "Grafana can detect ...", I believe it means that "With the Grafana plugin SDK for Go, a plugin can detect ...". That clarifies that it can detect the data frame type _if_ you are using a backend for your plugin (this is, the library is written in go).
 - For detecting and converting a data frame, we could give an example:

```go
		tsSchema := frame.TimeSeriesSchema()
		if tsSchema.Type == data.TimeSeriesTypeLong {
			wideFrame, err := data.LongToWide(frame, nil)
			if err == nil {
				// handle error
			}
			// return wideFrame
		}
``` 

> Or does the timeseries visualization always convert dataframes to wide?

I don't think this happens but I am no expert of the timeseries visualization so maybe it's the case.

> I think it'd also be good to mention here that if developers want to their dataframes to support alerting they need to use wide dataframes

I was not aware of this either.
