### ISSUE TITLE
Bug: supervisord.conf generated wrong executable names for GitHub datasource

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/plugin-tools#907]
### Which package(s) does this bug affect?

- [X] Create Plugin
- [ ] Sign Plugin
- [ ] Plugin E2E
- [ ] Plugin Meta Extractor

### Package versions

```shell
4.10.3
```

### What happened?

While updating the create-plugin to the latest version in the github datasource I found that the supervisord.conf generated wrong executable names for it.

**Wrong**
`command=bash -c 'while [ ! -f /root/grafana-github-datasource/dist/gpx_git-hub* ]; do sleep 1; done; /run.sh'`

**Correct**
`command=bash -c 'while [ ! -f /root/grafana-github-datasource/dist/gpx_github* ]; do sleep 1; done; /run.sh'`

### What you expected to happen

I expected the right executable to be there.

### How to reproduce it (as minimally and precisely as possible)

Update create-plugin in github datasource. See https://github.com/grafana/github-datasource/pull/305

### Environment

```shell
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M2
    Memory: 3.77 GB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.13.1/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    pnpm: 8.14.0 - ~/.nvm/versions/node/v20.13.1/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.158
    Safari: 17.4.1
```

**Comment by tolzhabayev** [comment]
@oshirohugo please take a look, maybe can be done as part of https://github.com/grafana/plugin-tools/pull/910 or after that.
