### ISSUE TITLE
Feat: Support wasm files when bundling plugins

### ISSUE THREAD

**Issue by jackw** [grafana/plugin-tools#933]
### Which areas does this feature request relate to

- [X] Create Plugin
- [ ] Sign Plugin
- [ ] Plugin E2E
- [ ] Plugin Meta Extractor
- [ ] Documentation

### Problem

Machine learning related projects/libraries can contain wasm files that the current webpack config doesn't know how to handle. Rather than expect plugin developers to customise their configs for these libraries it's probably better that we support it out the box.

### Solution

Update the config to support wasm. Webpack has multiple options here:

1. Use [`experiments.asyncWebAssembly`](https://webpack.js.org/configuration/experiments/#experiments).
2. Use [`asset/resource`](https://webpack.js.org/guides/asset-modules/#resource-assets).

### Are you interested in contributing the solution?

- [ ] Yes
- [ ] No

**Comment by sd2k** [comment]
Interestingly I see zero difference in the generated module.js when using `experiments.asyncWebAssembly` vs `asset/resource` :shrug:

Given that the `asyncWebAssembly` flag will default to `true` in the next version of Webpack it feels like it might be the better call, as there may be future WASM-based optimizations built in to Webpack.
