### ISSUE TITLE
ERR_UNKNOWN_BUILTIN_MODULE

### ISSUE THREAD

**Issue by cpgarcia518** [grafana/plugin-tools#938]
![image](https://github.com/grafana/plugin-tools/assets/50991879/71f1011a-5d54-416b-971c-44fb4a94677a)
I got this error??

**Comment by tolzhabayev** [comment]
Hey @cpgarcia518,

can you provide which node version you are using?

**Comment by cpgarcia518** [comment]
Version 10.3.1

**Comment by tolzhabayev** [comment]
Closing as the fix would be to move to node 20. Please reopen / comment if that does not solve the problem.
