### ISSUE TITLE
Docs: Create page detailing how plugins can use RBAC 

### ISSUE THREAD

**Issue by jackw** [grafana/plugin-tools#988]
### Which areas does this feature request relate to

- [ ] Create Plugin
- [ ] Sign Plugin
- [ ] Plugin E2E
- [ ] Plugin Meta Extractor
- [X] Documentation

### Problem

There is no docs page that details how a plugin developer can use RBAC in their plugin.

### Solution

Create a page in our docs website that explains how developers can use this feature. The [rbac example readme](https://github.com/grafana/grafana-plugin-examples/blob/main/examples/app-with-rbac/README.md) is quite extensive and could likely be used as reference. We could probably align this with the release of the new RBAC frontend interface due in Grafana 11.2.0.

### Are you interested in contributing the solution?

- [ ] Yes
- [ ] No

**Comment by tolzhabayev** [comment]
@jackw can we adjust the example, especially this part https://github.com/grafana/grafana-plugin-examples/blob/main/examples/app-with-rbac/README.md#perform-access-control-checks-in-the-frontend now that we have https://github.com/grafana/grafana/pull/89047?

**Comment by jackw** [comment]
> @jackw can we adjust the example, especially this part https://github.com/grafana/grafana-plugin-examples/blob/main/examples/app-with-rbac/README.md#perform-access-control-checks-in-the-frontend now that we have [grafana/grafana#89047](https://github.com/grafana/grafana/pull/89047)?

We can but shouldn't we wait for Grafana 11.2 to land before doing so?

**Comment by tomglenn** [comment]
Picking this one up and using @jackw's branch (https://github.com/grafana/grafana-plugin-examples/compare/main...jackw%2Fmigrate-rbac-runtime) as a reference. We may also need to create a separate docs page to cover RBAC in datasource plugins. As Jack mentioned we should hold off on merging these new docs until 11.2.
